config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"

  resources :newsletters, only: :create

  scope "(:locale)", locale: /fr|en/ do
    resources :pages, only: :show
    get "10-principles", to: "pages#show", as: "principles", defaults: { id: "10-principles"}
    get "french-burners", to: "pages#show", as: "frenchburners", defaults: { id: "frenchburners"}
    get "burning-man", to: "pages#show", as: "burningman", defaults: { id: "burningman" }

    resources :articles, only: [:index, :show]

    namespace :admin do
      resources :newsletters, only: [:index, :destroy]
      resources :users, only: [:index, :destroy]
      resources :slideshows, only: [:index, :create, :destroy]
      resources :articles, except: [:show]
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

  translates :title, :content

  belongs_to :user

  scope :published, -> { where( status: "published") }
  scope :archived, -> { where( status: "archived") }
  scope :draft, -> { where( status: "draft") }

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true, format: {with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/}
end

app/models/slideshow.rb
class Slideshow < ActiveRecord::Base
  mount_uploader :picture, SlideshowUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :authenticate_user!
  before_action :is_admin?

  layout "admin"

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def is_admin?
    redirect_to root_url, flash: {error: t('admin.not_enough_right')} if current_user.role != "admin"
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::AdminController

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build article_params
    if @article.save
      redirect_to admin_articles_url, flash: {success: I18n.t('articles.flash.create_success')}
    else
      flash[:error] = I18n.t('articles.flash.create_fail')
      render :new
    end
  end

  def edit
    @article = Article.find_by_id( params[:id] )
    @article ? render(:edit) : redirect_to(admin_articles_url)
  end

  def update
    @article = Article.find_by_id( params[:id] )
    if @article && @article.update_attributes(article_params)
      redirect_to admin_articles_url, flash: {success: I18n.t('articles.flash.update_success')}
    else
      flash[:error] = I18n.t('articles.flash.update_fail')
      render :edit
    end
  end

  def destroy
    @article = Article.find_by_id( params[:id] )
    @article.destroy ? flash[:success] = I18n.t('articles.flash.delete_success') : flash[:error] = I18n.t('articles.flash.delete_fail')
    redirect_to admin_articles_url
  end

  def article_params
    params.require(:article).permit(:title, :content, :publish_date, :status)
  end
end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < Admin::AdminController

  def index
    @newsletters = Newsletter.all
  end

  def delete
    newsletter = Newsletter.find(:id)
    newsletter.destroy ? flash[:success] = t('newsletter.flash.delete_success') : flash[:error] = t('newsletter.flash.delete_fail')
    redirect_to admin_newsletters_url
  end

end

app/controllers/admin/slideshows_controller.rb
class Admin::SlideshowsController < Admin::AdminController
  def index
    @slideshows = Slideshow.all
    @slideshow = Slideshow.new
  end

  def create
    slideshow = Slideshow.new slideshow_params
    slideshow.save ? flash[:success] = t('slideshow.flash.create_success') : flash[:error] = t('slideshow.flash.create_fail')
    redirect_to admin_slideshows_url
  end

  def destroy
    slideshow = Slideshow.find_by_id params[:id]
    slideshow && slideshow.destroy ? flash[:success] = t('slideshow.flash.delete_success') : flash[:error] = t('slideshow.flash.delete_fail')
    redirect_to admin_slideshows_url
  end

  private
    def slideshow_params
      params.require(:slideshow).permit(:picture, :url)
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale
  before_action :newsletter

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def newsletter
    @newsletter = Newsletter.new
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.published.order( "publish_date DESC" )
  end

  def show
    @article = Article.published.find_by_id(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @slideshows = Slideshow.all
  end

end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController

  def create
    newsletter = Newsletter.new newsletter_params
    newsletter.save ? flash[:success] = t('newsletter.flash.create_success') : flash[:error] = t('newsletter.flash.create_fail')
    redirect_to root_url
  end

  private
    def newsletter_params
      params.require(:newsletter).permit(:email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    render params[:id]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      hard_wrap: true,
      filter_html: true
    }
    extensions = {
      autolink: true,
      tables: true,
      underline: true,
      highlight: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    @markdown ||= Redcarpet::Markdown.new(renderer, extensions)
    @markdown.render(text).html_safe
  end

  def markdown_for_index(text)
    options = {
      hard_wrap: true,
      filter_html: true
    }
    extensions = {
      autolink: true,
      tables: true,
      underline: true,
      highlight: true
    }
    renderer = Redcarpet::Render::HTML.new(options)
    @markdown_index ||= Redcarpet::Markdown.new(renderer, extensions)
    @markdown_index.render(text).html_safe
  end

end

app/views/admin/articles/_form.html.haml
.form-group
  = builder.label :title
  = builder.text_field :title, class: "form-control"
.form-group
  = builder.label :content
  = builder.text_area :content, class: "form-control", rows: 12
.form-group
  = builder.label :status
  = builder.select :status, [ [t('activerecord.attributes.article.statuses.draft'), "draft"],
    [t('activerecord.attributes.article.statuses.published'), "published"],
    [t('activerecord.attributes.article.statuses.archived'), 'archived'] ], {}, {class: "form-control"}
.form-group
  = builder.label :publish_date
  = builder.text_field :publish_date, class: "form-control datepicker", "data-locale" => I18n.locale

app/views/admin/articles/edit.html.haml
#article_edit
  .panel.panel-default
    .panel-heading
      %h3.panel-title= t('.edit_title')
    .panel-body
      = form_for [:admin, @article] do |f|
        = render partial: "form", locals: {builder: f}
        = f.submit t('.submit'), class: "btn btn-default"

app/views/admin/articles/index.html.haml
#article_index
  %p= link_to t('.add'), new_admin_article_url, class: "btn btn-success"
  .panel.panel-default
    .table-responsive
      %table.table.table-striped.table-hovered
        %thead
          %tr
            %th #
            %th= t('activerecord.attributes.article.title')
            %th= t('activerecord.attributes.article.publish_date')
            %th= t('activerecord.attributes.article.status')
            %th= t('.action')

        - @articles.each_with_index do |article, index|
          %tr
            %th= index
            %td= article.title
            %td= article.publish_date
            %td= t('activerecord.attributes.article.statuses.' + article.status)
            %td
              = link_to t('.edit'), edit_admin_article_url(article)
              = link_to t('.delete'), admin_article_url(article), method: :delete

app/views/admin/articles/new.html.haml
#article_new
  .panel.panel-default
    .panel-heading
      %h3.panel-title= t('.add_title')
    .panel-body
      = form_for [:admin, @article] do |f|
        = render partial: "form", locals: {builder: f}
        = f.submit t('.submit'), class: "btn btn-default"

app/views/admin/newsletters/index.html.haml
#newsletter_index
  .panel.panel-default
    .table-responsive
      %table.table.table-striped.table-hovered
        %thead
          %tr
            %th #
            %th= t('.email')
            %th= t('.created_at')
            %th= t('.action')

        - @newsletters.each_with_index do |newsletter, index|
          %tr
            %th= index
            %td= newsletter.email
            %td= newsletter.created_at
            %td= link_to t('.delete'), admin_newsletter_url(newsletter), method: :delete

app/views/admin/shared/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "French Burners", admin_newsletters_url, class: "navbar-brand"
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li{class: params[:controller] == "admin/newsletters" ? "active" : ""}= link_to t('.newsletter'), admin_newsletters_url
        %li{class: params[:controller] == "admin/users" ? "active" : ""}= link_to t('.users'), admin_users_url
        %li{class: params[:controller] == "admin/slideshow" ? "active" : ""}= link_to t('.slideshow'), admin_slideshows_url
        %li{class: params[:controller] == "admin/articles" ? "active" : ""}= link_to t('.articles'), admin_articles_url
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Dropdown
            %span.caret
          %ul.dropdown-menu
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} Separated link
            %li.divider{:role => "separator"}
            %li
              %a{:href => "#"} One more separated link
      %ul.nav.navbar-nav.navbar-right
        %li
          %button.btn.btn-default.navbar-btn{:type => "button"} Sign out
- flash.each do |flash_type, flash_text|
  = content_tag(:p, flash_text, :class => "flash #{flash_type}")

app/views/admin/slideshows/index.html.haml
#slideshow_index
  .panel.panel-default.new
    %h2= t('.create_title')
    = form_for [:admin, @slideshow] do |f|
      .form-group
        = f.label :picture, t('.picture_label')
        = f.file_field :picture
        .help-block= t('.picture_help')
      .form-group
        = f.label :url, t('.url_label')
        = f.text_field :url, placeholder: t('.url_placeholder'), class: "form-control"
      = f.submit t('.submit'), class: "btn btn-default"
  .panel.panel-default.list
    .row
      - @slideshows.each do |slideshow|
        .col-sm-6.col-md-4
          .thumbnail
            = image_tag slideshow.picture.url(:thumb)
            .caption
              %p= slideshow.url
              %p
                = link_to t('.delete'), admin_slideshow_url(slideshow), class: "btn btn-primary", role: "button", method: :delete

app/views/admin/users/index.html.haml
#user_index
  .panel.panel-default
    .table-responsive
      %table.table.table-striped.table-hovered
        %thead
          %tr
            %th #
            %th= t('.email')
            %th= t('.created_at')
            %th= t('.role')
            %th= t('.action')

        - @users.each_with_index do |user, index|
          %tr
            %th= index
            %td= user.email
            %td= user.created_at
            %td= user.role
            %td= link_to t('.delete'), admin_user_url(user), method: :delete

app/views/articles/index.html.haml
#article_index
  .article_list
    -@articles.each do |article|
      .article
        %h1= link_to article.title, article_url(article)
        %p.subtitle
          - if article.publish_date
            %span.date= t('.date', date: l(article.publish_date, format: :long))
          %span.author= t('.author', author: article.user.email)
        .content
          = markdown_for_index(article.content.truncate(1000))
          .read_next
            = link_to t('.read_next'), article_url(article)

app/views/articles/show.html.haml
#article_show
  %h1.page-title= @article.title
  .content
    = markdown(@article.content)

app/views/home/index.html.haml
#home_index
  #slideshow
    %ul{ :style => "width: #{@slideshows.count * 100}%;"}
      -@slideshows.each do |slideshow|
        %li
          = link_to "", slideshow.url.blank? ? "#" : slideshow.url, style: "background-image: url(#{slideshow.picture.url(:slide)});", class: "image resizable-slideshow"
    .next
      %p.image
    .previous
      %p.image

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    = csrf_meta_tags
    %title French Burners admin
    = stylesheet_link_tag "admin", :media => 'all'
    = javascript_include_tag "admin"
    = csrf_meta_tags

  %body
    = render partial: 'admin/shared/header'
    = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frenchburners</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,400,700,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: "shared/header" %>
  <%= yield %>
  <%= render partial: "shared/footer" %>

</body>
</html>

app/views/pages/10-principles.html.haml
#page_show
  #10-principles
    %h1.page-title Les 10 principes de Burning Man
    = image_tag "10_principles.jpg", alt: "10 principes burning man", height: "283", title: "10 principes burning man", width: "1408"
    %p.principles
      \.
      %br/
      %strong 1. Ouverture à tous :
      nous acceptons tout le monde
      %br/
      %strong 2. Immédiateté :
      nous faisons la part belle à l’expérience, dans l’instant présent
      %br/
      %strong 3. Participation :
      chacun est encouragé à ne pas être un simple spectateur, s’exprimer en créant,… : nos événements sont la somme des participations de chacun
      %br/
      %strong 4. Expression personnelle radicale :
      chacun peut s’exprimer librement, sans être jugé
      %br/
      %strong 5. Autonomie :
      chacun se prend en charge sans compter à priori sur les autres, sachant qu’il pourra toujours compter sur eux en cas de nécessité
      %br/
      %strong 6. Civisme :
      chacun doit avoir un comportement civique et respectueux des autres
      %br/
      %strong 7. Ne laisser aucune trace :
      on ne laisse aucune trace lors de nos événements
      %br/
      %strong 8. Non commercial :
      nous excluons toute forme de commerce, de publicité, de sponsoring ou d’activités commerciales
      %br/
      %strong 9. Don :
      le don sans attente de retour
      %br/
      %strong 10. Effort commun :
      actions collectives au travers de la collaboration, du bénévolat, de l’entraide
      %br/
      \.
    %p
      %strong BURNING MAN encourage ses équipes et les 70 000 participants à utiliser des énergies renouvelables, des combustibles non fossiles, à recycler et à composter les déchets et matières organiques.
    %h2 Pendant BURNING MAN
    %p Le respect de l'environnement est très concret pendant BURNING MAN :
    %ul
      %li
        %strong Principe du "Leave no trace" pour laisser un désert intact à la fin
        \: on ne laisse rien dans le désert (même pas des mégots de cigarette, ni des plumes de boa), et on rapporte même ses eaux usées afin qu'elles ne souillent pas (savon, eau de vaisselle, ...) le désert.
      %li
        Beaucoup de participants se déplacent avec leur propre gobelet: c'est le
        %strong "Bring Your Own Cup"
        qui vise à réduire les déchets à base de verres en plastique,
      %li BURNING MAN utilise de l'énergie solaire, ainsi que certains participants,
      %li Certaines installations sont mues par l'énergie de personnes qui pédalent,
      %li BURNING MAN pratique le tri sélectif: par exemple les canettes sont triées et compactées sur place grâce des bénévoles qui pédalent,
      %li
        70 000 personnes se déplacent à vélo pendant BURNING MAN,
        %br/
        \.
    %h2 Après BURNING MAN
    %p Le respect de l'environnement, c'est aussi après BURNING MAN :
    %ul
      %li Les participants ont été sensibilisés pendant une semaine, et ils ont même "pratiqué": ils appliquent ces principes de retour chez eux,
      %li Les événements "BURNING MAN" dans le monde appliquent les mêmes principes,
      %li BURNING MAN offre de l'énergie solaire au travers de la fondation BLACK ROCK SOLAR.
    %p
      %strong ET AUSSI
      %br/
      BURNING MAN fait la promotion des 6 R
    %ul
      %li
        %strong Respecter
        (les gens, les animaux, la terre, la nature,...)
      %li
        %strong Repenser
        (le coût environnemental avant d'acheter, ses besoins, ses alternatives avant d'acheter,..)
      %li
        %strong Réduire
        (la quantité de déchets)
      %li
        %strong Réutiliser
        (avant de jeter à la poubelle, se demander si l'on ne pourra le ré-utiliser)
      %li
        %strong Recycler
        (canettes, verre, compost..)
      %li
        %strong Restaurer
        (essayer que les lieux où on passe soient plus propres après notre passage qu'avant).
    %p
      %strong THEME 2007
      %br/
      En 2007, le thème de BURNING MAN était justement "THE GREEN MAN", avec la mise en œuvre de solutions alternatives au niveau énergétique, et la démonstration par des entreprises de solutions alternatives viables économiquement.
    %p
      %strong FONDATION
      %br/
      BLACK ROCK SOLAR est une des fondations de BURNING MAN, dédiée à fournir de l'énergie solaire aux plus défavorisés (donation, installation de panneaux solaires).
    = link_to "En savoir plus", "http://burningman.org/culture/philosophical-center/10-principles/", class: "btn btn-default", target: "_blank"

app/views/pages/burningman.html.haml
#page_show
  #burning-man
    %h1.page-title Burning Man
    = image_tag "illustration-bm.jpg"
    %h2 Historique
    %p Le rassemblement a commencé en 1986 sur une plage de San Francisco, et aujourd'hui ce sont 70 000 personnes qui convergent chaque année, fin août, dans un désert du Nevada, pour créer une ville éphémère qui surgit de nulle part pour une semaine, à 7 heures de route de San Francisco.
    %p Burning Man est une communauté temporaire, dédiée à des formes radicales d'auto-expression et d'autosuffisance. Dans un environnement surnaturel où l’argent est exclu, Burning Man peut aussi être vu comme une forme d’utopie artistique et festive.
    %p
      Burning man est une utopie contemporaine éphémère qui se déroule à Black Rock City, ville sortie du désert pour 7 jours de rupture avec la vie de tous les jours. Créativité et partage sont les maîtres mots du Burning Man, expérience qui parait unique dans un cadre exceptionnel.
      = image_tag "BMskyview.jpg", class: "left_image"
    %p
      %strong Il y a quelques règles à respecter :
    %ul
      %li
        %p
          %strong Self reliance (autonomie) :
          Il n'y a pas d'argent a Burning Man, il est donc impossible de faire de transactions marchandes. Il faut amener son eau et sa nourriture pour toute la durée du festival ainsi qu'un peu plus pour offrir aux autres en cas de besoin. Partage.
      %li
        %p
          %strong No spectator :
          Burning Man n'est pas un festival comme les autres et vise à promouvoir la créativité et la spontanéité de chacun. On ne peut donc y venir en simple spectateur mais il faut prendre une part active à l’expérience : avoir un morceau de musique à jouer, des choses à offrir comme des art-performances, des œuvres à exposer dans le désert... L'idée est de stimuler aux maximum la créativité de tous jusqu'à l'émulation.
      %li
        %p
          %strong Leave no trace :
          Ne laisser aucune trace dans le désert après le festival afin d'éviter de polluer ce site magnifique. Des centaines de volontaires restent pendant plusieurs semaines afin de nettoyer le site.
    = link_to "Voir les 10 principes", principles_url, class: "btn"

    %p
      = image_tag "french_burners_3.jpg", class: "right_image"
      Des centaines d'installations artistiques jaillissent au milieu du désert, exposées anonymement par des artistes:
    %p Mais ces oeuvres peuvent aussi etre créées par tout un chacun. En effet, la participation de chacun est encouragée: expression personnelle radicale et créativité! Chacun peut se révéler une âme d'artiste, créer et exposer son oeuvre !
    %p Programme ou non à la main, on se déplace parmi les centaines de "camps à thème" qui proposent des milliers de happenings et d'activités permettant de faire l'expérience de nombreuses choses plus ou moins sérieuses ou délirantes!
    %p
      Les seuls véhicules autorisées à se déplacer au sein de Burning Man sont
      %strong les véhicules mutants :
    %p
      %strong On croise ainsi des "véhicules" invraisemblables :
      bateaux, requins, baleines... qui en plus sont magnifiquement éclairés la nuit.
    %p
      Les habitants de cette ville éphémère sont
      = succeed "..." do
        %strong souriants, joyeux, aimables
      = succeed "." do
        %strong utopie
    %p
      Ce n'est ni trop grand (i.e. on se déplace en vélo), ni trop étriqué car ses
      %strong 70 000
      personnes sont réparties sur une surface de
      = succeed "." do
        %strong 4 km x 4 km
    %p Les conditions de vie sont généralement agréables. Les températures - aux alentours de 35°C - sont tout à fait supportables car l'air est sec et il règne en permanence un petit vent salvateur. Mais on ne peut exclure des conditions difficiles par moment, notamment lors des tempêtes de sable. Celles-ci apportent une certaine magie lorsqu'elles se présentent mais elles mettent à rude épreuve le campement et la vision qui nécessitent des "goggles" (i.e. lunettes d'aviateur ou lunettes de ski). Les nuits peuvent également se révéler froides lorsqu'il vente, mais il n'est pas rare de pouvoir être torse nu jusqu'à 2 heures du matin.
    %p On se préparera avec minutie pour BURNING MAN car l’événement a lieu dans un désert où l’on ne peut rien acheter. On pourra juste acheter de la glace pour conserver ses aliments frais dans des glacières et du café & thé au Center Camp. En dehors de cela, c'est la générosité qui prime : tout est offert par tout un chacun: cocktail, hot dog,...
    %p Afin de bien s'intégrer, on se préparera des tenues spéciales pour le jour et la nuit. Il s'agit de se fondre dans le désert et de faire perdurer ce dress-code délirant qui est la première forme de spectacle à BURNING MAN.
    = link_to "Autres évènements Burners autour de la france", "#", class: "btn"

app/views/shared/_footer.html.haml
#footer
  .content
    .box
      %h2= t('.community_title')
      %ul.communities
        %li= link_to t('.nice'), "https://www.facebook.com/groups/frenchburnersnice", target: "_blank"
        %li= link_to t('.montpellier'), "https://www.facebook.com/groups/215456928623052", target: "_blank"
        %li= link_to t('.alsace'), "https://www.facebook.com/FlamnKitsch", target: "_blank"
        %li= link_to t('.toulouse'), "https://www.facebook.com/groups/southwestfrenchburners", target: "_blank"
    .box
      %h2= t('.social_title')
      %ul.social
        %li= link_to t('.twitter'), "https://twitter.com/frenchburners", target: "_blank", class: "twitter"
        %li= link_to t('.facebook'), "https://www.facebook.com/frenchburners", target: "_blank", class: "facebook"
    .box
      %h2= t('.subscription_title')
      = form_for @newsletter do |f|
        = f.text_field :email, placeholder: t('.email_placeholder')
        = f.submit t('.subscribe')
    .clearette
  .copyright
    %p
      = t('.love')
      %span= link_to t('.lama'), 'http://redlama.fr', target: "_blank"

app/views/shared/_header.html.haml
#header
  %p.logo= link_to image_tag("logo.png"), root_url
  %ul#menu
    %li.parent
      %span{class: params[:controller] == "pages" && (params[:id] == "frenchburners" || params[:id] == "burningman") ? "active" : ""}= t('.presentation')
      %ul.childs.hide
        %li= link_to "French Burners", frenchburners_url
        %li= link_to "Burning Man", burningman_url
    %li= link_to t('.principles'), principles_url, class: params[:controller] == "pages" && params[:id] == "10-principles" ? "active" : ""
    %li= link_to t('.blog'), articles_url, class: params[:controller] == "articles" ? "active" : ""
    %li= link_to t('.events'), "#"
    %li= link_to t('.gallery'), "#"
    %li= link_to t('.contact'), "#"
  .login
    - if user_signed_in?
      %p.administration= link_to t('.administration'), admin_newsletters_url
      %p.logout= link_to t('.logout'), destroy_user_session_url, method: :delete
    - else
      %p.auth= link_to t('.login'), new_user_session_url
  .lang
    = link_to "fr", url_for(params.merge(locale: 'fr')), class: I18n.locale == :fr ? "active" : ""
    %span
      |
    = link_to "en", url_for(params.merge(locale: 'en')), class: I18n.locale == :en ? "active" : ""

  .clearette
  - flash.each do |flash_type, flash_text|
    = content_tag(:p, flash_text, :class => "flash #{flash_type}")